import type {
  AnnonceRecrutement,
  ChatMessage,
  Club,
  ClassementClub,
  Conversation,
  LiveMatch,
  MatchRapide,
  MessagePrive,
  Post,
  Story,
  Tournoi,
  Transfert,
  Joueur,
} from "@/types";

// ---------------------------------------------------------------------------
// CLUBS
// ---------------------------------------------------------------------------

export const clubs: Club[] = [
  {
    id: "african-fc",
    nom: "African FC",
    tag: "AFC",
    logo: "AFC",
    banniere: "afc",
    couleurPrincipale: "#0f9d58",
    couleurSecondaire: "#d4af37",
    description:
      "African FC est un projet ambitieux né d'une conviction : le continent africain regorge des meilleurs talents Pro Clubs au monde. Notre mission est de rassembler une génération de joueurs d'exception, disciplinés et compétitifs, pour dominer les plus hautes divisions et les tournois internationaux.",
    region: "Côte d'Ivoire",
    palmares: [
      "Champion Ligue Continentale 2025",
      "Vainqueur Coupe des Nations Pro Clubs 2025",
      "Finaliste World Clubs Cup 2024",
      "3x Champion Division Élite",
    ],
    fondation: "2023",
    followers: 48200,
    verifie: true,
    vitrine: true,
    classementElo: 2840,
    classementRang: 1,
    effectif: ["j1", "j2", "j3", "j4", "j5", "j6", "j7", "j8"],
    posteRecherche: [
      { poste: "BU", archetype: "Finisseur", niveauMin: 85, pourvu: false },
      { poste: "MOC", archetype: "Le Dix", niveauMin: 88, pourvu: false },
      { poste: "DC", archetype: "Défenseur Physique", niveauMin: 80, pourvu: true },
      { poste: "GB", archetype: "Gardien Réflexes", niveauMin: 82, pourvu: false },
    ],
    stats: {
      matchsJoues: 142,
      victoires: 118,
      nuls: 14,
      defaites: 10,
      butsMarques: 412,
      butsEncaisses: 96,
    },
    resultats: [
      {
        id: "r1",
        adversaireId: "c2",
        adversaireNom: "Dragons Élite",
        adversaireLogo: "DE",
        score: "4",
        scoreAdversaire: "1",
        date: "2026-08-14",
        competition: "Ligue Continentale",
        resultat: "Victoire",
      },
      {
        id: "r2",
        adversaireId: "c3",
        adversaireNom: "Nova United",
        adversaireLogo: "NU",
        score: "2",
        scoreAdversaire: "2",
        date: "2026-08-10",
        competition: "Coupe des Nations",
        resultat: "Nul",
      },
      {
        id: "r3",
        adversaireId: "c4",
        adversaireNom: "Phoenix Sporting",
        adversaireLogo: "PS",
        score: "5",
        scoreAdversaire: "0",
        date: "2026-08-05",
        competition: "Ligue Continentale",
        resultat: "Victoire",
      },
    ],
  },
  {
    id: "c2",
    nom: "Dragons Élite",
    tag: "DGE",
    logo: "DE",
    banniere: "dragons",
    couleurPrincipale: "#dc2626",
    couleurSecondaire: "#1c1c1c",
    description: "Club historique de la scène Pro Clubs européenne, exigeant et discipliné.",
    region: "France",
    palmares: ["Champion Division 1 2024", "Vainqueur Coupe de Printemps 2025"],
    fondation: "2021",
    followers: 21500,
    verifie: true,
    classementElo: 2690,
    classementRang: 2,
    effectif: ["j9", "j10", "j11"],
    posteRecherche: [
      { poste: "AD", archetype: "Ailier Rapide", niveauMin: 75, pourvu: false },
      { poste: "MDC", archetype: "Sentinelle", niveauMin: 78, pourvu: false },
    ],
    stats: { matchsJoues: 130, victoires: 96, nuls: 18, defaites: 16, butsMarques: 340, butsEncaisses: 150 },
    resultats: [],
  },
  {
    id: "c3",
    nom: "Nova United",
    tag: "NVU",
    logo: "NU",
    banniere: "nova",
    couleurPrincipale: "#2563eb",
    couleurSecondaire: "#facc15",
    description: "Jeune club ambitieux, mélange de talents belges et suisses.",
    region: "Belgique",
    palmares: ["Promu Division 2 2025"],
    fondation: "2024",
    followers: 8900,
    verifie: false,
    classementElo: 2410,
    classementRang: 5,
    effectif: ["j12", "j13"],
    posteRecherche: [{ poste: "BU", archetype: "Poacher", niveauMin: 70, pourvu: false }],
    stats: { matchsJoues: 84, victoires: 50, nuls: 12, defaites: 22, butsMarques: 190, butsEncaisses: 130 },
    resultats: [],
  },
  {
    id: "c4",
    nom: "Phoenix Sporting",
    tag: "PHX",
    logo: "PS",
    banniere: "phoenix",
    couleurPrincipale: "#f97316",
    couleurSecondaire: "#111827",
    description: "Club canadien reconnu pour son style de jeu offensif et spectaculaire.",
    region: "Canada",
    palmares: ["Champion Ligue Nord-Américaine 2023"],
    fondation: "2020",
    followers: 15200,
    verifie: true,
    classementElo: 2550,
    classementRang: 3,
    effectif: ["j14"],
    posteRecherche: [],
    stats: { matchsJoues: 160, victoires: 100, nuls: 20, defaites: 40, butsMarques: 380, butsEncaisses: 220 },
    resultats: [],
  },
  {
    id: "c5",
    nom: "Atlas Warriors",
    tag: "ATW",
    logo: "AW",
    banniere: "atlas",
    couleurPrincipale: "#059669",
    couleurSecondaire: "#b91c1c",
    description: "Le fer de lance du Pro Clubs marocain, en pleine ascension.",
    region: "Maroc",
    palmares: ["Champion Coupe du Maghreb 2025"],
    fondation: "2022",
    followers: 12300,
    verifie: true,
    classementElo: 2480,
    classementRang: 4,
    effectif: [],
    posteRecherche: [{ poste: "DD", archetype: "Latéral Offensif", niveauMin: 72, pourvu: false }],
    stats: { matchsJoues: 110, victoires: 70, nuls: 20, defaites: 20, butsMarques: 260, butsEncaisses: 140 },
    resultats: [],
  },
  {
    id: "c6",
    nom: "Titan FC",
    tag: "TTN",
    logo: "TF",
    banniere: "titan",
    couleurPrincipale: "#7c3aed",
    couleurSecondaire: "#f8fafc",
    description: "Club suisse réputé pour la solidité défensive de son effectif.",
    region: "Suisse",
    palmares: [],
    fondation: "2023",
    followers: 5400,
    verifie: false,
    classementElo: 2210,
    classementRang: 8,
    effectif: [],
    posteRecherche: [],
    stats: { matchsJoues: 60, victoires: 30, nuls: 10, defaites: 20, butsMarques: 110, butsEncaisses: 100 },
    resultats: [],
  },
];

// ---------------------------------------------------------------------------
// JOUEURS
// ---------------------------------------------------------------------------

export const joueurs: Joueur[] = [
  {
    id: "j1",
    pseudo: "Kwame_Finisher",
    avatar: "j1",
    bannerColor: "#0f9d58",
    poste: "BU",
    archetype: "Finisseur",
    styleDeJeu: "Percussion et sang-froid devant le but",
    noteGlobale: 91,
    region: "Côte d'Ivoire",
    disponibilite: "Soir (19h-23h)",
    statut: "En club",
    niveauPro: 87,
    niveauProMax: 92,
    division: "Champions",
    langues: ["Français", "Anglais"],
    bio: "Buteur né. Objectif : devenir le meilleur réalisateur de la Ligue Continentale avec African FC.",
    followers: 12400,
    following: 320,
    verifie: true,
    historiqueClubs: [
      { clubId: "african-fc", clubNom: "African FC", clubLogo: "AFC", periode: "2024 - présent", poste: "BU", statut: "Actuel" },
      { clubId: "c5", clubNom: "Atlas Warriors", clubLogo: "AW", periode: "2023 - 2024", poste: "BU", statut: "Ancien" },
    ],
    badges: [
      { id: "b1", label: "Buteur confirmé", icon: "Target", color: "gold" },
      { id: "b2", label: "Homme du match x12", icon: "Star", color: "green" },
    ],
    videos: [
      { id: "v1", titre: "Triplé décisif vs Dragons Élite", url: "#", plateforme: "YouTube", vues: 8400, date: "2026-08-14" },
      { id: "v2", titre: "Best Goals Saison 5", url: "#", plateforme: "Twitch", vues: 15200, date: "2026-07-01" },
    ],
    evaluations: [
      { id: "e1", parId: "j9", parPseudo: "LeoDefender", fairPlay: 5, ponctualite: 5, niveau: 5, commentaire: "Machine à buts, très fair-play.", date: "2026-08-14" },
    ],
    stats: { matchsJoues: 142, buts: 118, passesD: 34, victoires: 118, defaites: 10, noteMoyenneMatch: 8.4, tauxVictoire: 83 },
  },
  {
    id: "j2",
    pseudo: "Sekou_Playmaker",
    avatar: "j2",
    bannerColor: "#d4af37",
    poste: "MOC",
    archetype: "Le Dix",
    styleDeJeu: "Vision de jeu et passes millimétrées",
    noteGlobale: 89,
    region: "Sénégal",
    disponibilite: "Soir et week-end",
    statut: "En club",
    niveauPro: 84,
    niveauProMax: 90,
    division: "Champions",
    langues: ["Français", "Anglais"],
    bio: "Le cerveau du milieu African FC. Créateur de jeu avant tout.",
    followers: 9800,
    following: 210,
    verifie: true,
    historiqueClubs: [
      { clubId: "african-fc", clubNom: "African FC", clubLogo: "AFC", periode: "2024 - présent", poste: "MOC", statut: "Actuel" },
    ],
    badges: [{ id: "b3", label: "Meilleur passeur", icon: "Sparkles", color: "green" }],
    videos: [{ id: "v3", titre: "Assist Show vs Nova United", url: "#", plateforme: "YouTube", vues: 5300, date: "2026-08-10" }],
    evaluations: [],
    stats: { matchsJoues: 138, buts: 42, passesD: 96, victoires: 112, defaites: 12, noteMoyenneMatch: 8.1, tauxVictoire: 81 },
  },
  {
    id: "j3",
    pseudo: "Yannick_Wall",
    avatar: "j3",
    bannerColor: "#0f9d58",
    poste: "DC",
    archetype: "Défenseur Physique",
    styleDeJeu: "Mur défensif, duels aériens",
    noteGlobale: 86,
    region: "Cameroun",
    disponibilite: "Soir (20h-00h)",
    statut: "En club",
    niveauPro: 79,
    niveauProMax: 85,
    division: "Élite",
    langues: ["Français"],
    bio: "Roc défensif d'African FC, peu de buts encaissés dans mon dos.",
    followers: 6200,
    following: 150,
    verifie: false,
    historiqueClubs: [
      { clubId: "african-fc", clubNom: "African FC", clubLogo: "AFC", periode: "2025 - présent", poste: "DC", statut: "Actuel" },
    ],
    badges: [{ id: "b4", label: "Mur défensif", icon: "Shield", color: "gray" }],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 98, buts: 4, passesD: 6, victoires: 78, defaites: 12, noteMoyenneMatch: 7.6, tauxVictoire: 79 },
  },
  {
    id: "j4",
    pseudo: "Boubacar_Fox",
    avatar: "j4",
    bannerColor: "#facc15",
    poste: "AD",
    archetype: "Ailier Rapide",
    styleDeJeu: "Vitesse pure et débordements",
    noteGlobale: 88,
    region: "Sénégal",
    disponibilite: "Soir",
    statut: "En club",
    niveauPro: 81,
    niveauProMax: 88,
    division: "Élite",
    langues: ["Français", "Anglais"],
    bio: "Le plus rapide du continent, dribbles et centres millimétrés.",
    followers: 7100,
    following: 190,
    verifie: true,
    historiqueClubs: [],
    badges: [],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 90, buts: 38, passesD: 44, victoires: 70, defaites: 14, noteMoyenneMatch: 7.9, tauxVictoire: 78 },
  },
  {
    id: "j5",
    pseudo: "Ibrahim_Keeper",
    avatar: "j5",
    bannerColor: "#0f9d58",
    poste: "GB",
    archetype: "Gardien Réflexes",
    styleDeJeu: "Réflexes surhumains, arrêts décisifs",
    noteGlobale: 87,
    region: "Côte d'Ivoire",
    disponibilite: "Week-end",
    statut: "En club",
    niveauPro: 76,
    niveauProMax: 83,
    division: "Élite",
    langues: ["Français"],
    bio: "Dernier rempart d'African FC. Zéro panique, que du sang-froid.",
    followers: 5400,
    following: 90,
    verifie: false,
    historiqueClubs: [],
    badges: [{ id: "b5", label: "Gardien fiable", icon: "ShieldCheck", color: "green" }],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 100, buts: 0, passesD: 2, victoires: 82, defaites: 10, noteMoyenneMatch: 7.8, tauxVictoire: 82 },
  },
  {
    id: "j6",
    pseudo: "Moussa_Engine",
    avatar: "j6",
    bannerColor: "#d4af37",
    poste: "MC",
    archetype: "Box-to-Box",
    styleDeJeu: "Infatigable, présent partout sur le terrain",
    noteGlobale: 85,
    region: "Côte d'Ivoire",
    disponibilite: "Soir",
    statut: "En club",
    niveauPro: 74,
    niveauProMax: 80,
    division: "Division 1",
    langues: ["Français"],
    bio: "Le poumon de l'équipe.",
    followers: 3100,
    following: 80,
    verifie: false,
    historiqueClubs: [],
    badges: [],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 76, buts: 12, passesD: 18, victoires: 55, defaites: 14, noteMoyenneMatch: 7.4, tauxVictoire: 72 },
  },
  {
    id: "j7",
    pseudo: "Didier_Rock",
    avatar: "j7",
    bannerColor: "#0f9d58",
    poste: "DG",
    archetype: "Latéral Offensif",
    styleDeJeu: "Percussions côté gauche, centres précis",
    noteGlobale: 83,
    region: "Côte d'Ivoire",
    disponibilite: "Soir et week-end",
    statut: "En club",
    niveauPro: 68,
    niveauProMax: 75,
    division: "Division 2",
    langues: ["Français"],
    bio: "Latéral moderne, autant utile en attaque qu'en défense.",
    followers: 2200,
    following: 60,
    verifie: false,
    historiqueClubs: [],
    badges: [],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 64, buts: 6, passesD: 20, victoires: 42, defaites: 16, noteMoyenneMatch: 7.2, tauxVictoire: 66 },
  },
  {
    id: "j8",
    pseudo: "Fode_Sentinel",
    avatar: "j8",
    bannerColor: "#d4af37",
    poste: "MDC",
    archetype: "Sentinelle",
    styleDeJeu: "Récupération et relance propre",
    noteGlobale: 84,
    region: "Sénégal",
    disponibilite: "Soir",
    statut: "En club",
    niveauPro: 70,
    niveauProMax: 77,
    division: "Division 1",
    langues: ["Français", "Anglais"],
    bio: "Le bouclier devant la défense.",
    followers: 1800,
    following: 55,
    verifie: false,
    historiqueClubs: [],
    badges: [],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 58, buts: 3, passesD: 14, victoires: 38, defaites: 12, noteMoyenneMatch: 7.1, tauxVictoire: 65 },
  },
  {
    id: "j9",
    pseudo: "LeoDefender",
    avatar: "j9",
    bannerColor: "#dc2626",
    poste: "DC",
    archetype: "Stopper",
    styleDeJeu: "Tacles chirurgicaux",
    noteGlobale: 82,
    region: "France",
    disponibilite: "Soir",
    statut: "En club",
    niveauPro: 65,
    niveauProMax: 71,
    division: "Division 3",
    langues: ["Français"],
    bio: "Défenseur central chez Dragons Élite.",
    followers: 1400,
    following: 70,
    verifie: false,
    historiqueClubs: [{ clubId: "c2", clubNom: "Dragons Élite", clubLogo: "DE", periode: "2023 - présent", poste: "DC", statut: "Actuel" }],
    badges: [],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 70, buts: 5, passesD: 4, victoires: 48, defaites: 18, noteMoyenneMatch: 7.0, tauxVictoire: 68 },
  },
  {
    id: "j10",
    pseudo: "MaxGoal_FR",
    avatar: "j10",
    bannerColor: "#dc2626",
    poste: "BU",
    archetype: "Poacher",
    styleDeJeu: "Sens du but affûté",
    noteGlobale: 85,
    region: "France",
    disponibilite: "Soir et week-end",
    statut: "Libre",
    niveauPro: 60,
    niveauProMax: 66,
    division: "Division 4",
    langues: ["Français", "Anglais"],
    bio: "Cherche un club ambitieux pour la saison 6. Dispo tout de suite.",
    followers: 980,
    following: 120,
    verifie: false,
    historiqueClubs: [{ clubId: "c2", clubNom: "Dragons Élite", clubLogo: "DE", periode: "2022 - 2025", poste: "BU", statut: "Ancien" }],
    badges: [{ id: "b6", label: "Buteur confirmé", icon: "Target", color: "gold" }],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 54, buts: 61, passesD: 8, victoires: 30, defaites: 16, noteMoyenneMatch: 7.5, tauxVictoire: 55 },
  },
  {
    id: "j11",
    pseudo: "Nathan_Wing",
    avatar: "j11",
    bannerColor: "#dc2626",
    poste: "AG",
    archetype: "Ailier Créatif",
    styleDeJeu: "Dribbles chaloupés, passes clés",
    noteGlobale: 80,
    region: "France",
    disponibilite: "Soir",
    statut: "En club",
    niveauPro: 55,
    niveauProMax: 60,
    division: "Division 5",
    langues: ["Français"],
    bio: "Ailier chez Dragons Élite.",
    followers: 640,
    following: 88,
    verifie: false,
    historiqueClubs: [],
    badges: [],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 40, buts: 14, passesD: 22, victoires: 22, defaites: 12, noteMoyenneMatch: 6.9, tauxVictoire: 55 },
  },
  {
    id: "j12",
    pseudo: "Tom_Vandaele",
    avatar: "j12",
    bannerColor: "#2563eb",
    poste: "MC",
    archetype: "Meneur de Jeu Profond",
    styleDeJeu: "Sang froid, longues transversales",
    noteGlobale: 78,
    region: "Belgique",
    disponibilite: "Week-end",
    statut: "En club",
    niveauPro: 48,
    niveauProMax: 55,
    division: "Division 6",
    langues: ["Français", "Anglais"],
    bio: "Milieu relayeur chez Nova United.",
    followers: 310,
    following: 45,
    verifie: false,
    historiqueClubs: [],
    badges: [],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 30, buts: 4, passesD: 12, victoires: 16, defaites: 10, noteMoyenneMatch: 6.6, tauxVictoire: 53 },
  },
  {
    id: "j13",
    pseudo: "Kilian_Ice",
    avatar: "j13",
    bannerColor: "#2563eb",
    poste: "GB",
    archetype: "Gardien Libéro",
    styleDeJeu: "Jeu au pied, sort de sa cage",
    noteGlobale: 79,
    region: "Suisse",
    disponibilite: "Soir",
    statut: "En essai",
    niveauPro: 44,
    niveauProMax: 50,
    division: "Division 7",
    langues: ["Français"],
    bio: "En essai chez Nova United cette semaine.",
    followers: 210,
    following: 30,
    verifie: false,
    historiqueClubs: [],
    badges: [],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 22, buts: 0, passesD: 1, victoires: 10, defaites: 9, noteMoyenneMatch: 6.4, tauxVictoire: 45 },
  },
  {
    id: "j14",
    pseudo: "JJ_Phoenix",
    avatar: "j14",
    bannerColor: "#f97316",
    poste: "BU",
    archetype: "Attaquant Cible",
    styleDeJeu: "Point de fixation, jeu de tête",
    noteGlobale: 81,
    region: "Canada",
    disponibilite: "Soir",
    statut: "En club",
    niveauPro: 52,
    niveauProMax: 58,
    division: "Division 6",
    langues: ["Anglais", "Français"],
    bio: "Avant-centre physique chez Phoenix Sporting.",
    followers: 450,
    following: 60,
    verifie: false,
    historiqueClubs: [],
    badges: [],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 45, buts: 30, passesD: 6, victoires: 26, defaites: 12, noteMoyenneMatch: 6.8, tauxVictoire: 58 },
  },
  {
    id: "j15",
    pseudo: "Amara_Diallo",
    avatar: "j15",
    bannerColor: "#059669",
    poste: "MOC",
    archetype: "Meneur de Jeu Avancé",
    styleDeJeu: "Dernière passe, frappes lointaines",
    noteGlobale: 83,
    region: "Sénégal",
    disponibilite: "Soir et week-end",
    statut: "Libre",
    niveauPro: 58,
    niveauProMax: 64,
    division: "Division 4",
    langues: ["Français", "Anglais"],
    bio: "Free agent, je cherche un club sérieux visant la montée en Élite.",
    followers: 720,
    following: 95,
    verifie: false,
    historiqueClubs: [],
    badges: [{ id: "b7", label: "Meilleur passeur", icon: "Sparkles", color: "green" }],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 38, buts: 16, passesD: 24, victoires: 20, defaites: 10, noteMoyenneMatch: 7.0, tauxVictoire: 53 },
  },
  {
    id: "moi",
    pseudo: "VousMeme",
    avatar: "moi",
    bannerColor: "#0f9d58",
    poste: "MOC",
    archetype: "Le Dix",
    styleDeJeu: "Créatif et technique",
    noteGlobale: 75,
    region: "France",
    disponibilite: "Soir",
    statut: "Libre",
    niveauPro: 34,
    niveauProMax: 34,
    division: "Division 8",
    langues: ["Français"],
    bio: "Nouveau sur Club Pro FC 27. Prêt à faire mes preuves !",
    followers: 12,
    following: 34,
    verifie: false,
    historiqueClubs: [],
    badges: [],
    videos: [],
    evaluations: [],
    stats: { matchsJoues: 12, buts: 4, passesD: 6, victoires: 6, defaites: 5, noteMoyenneMatch: 6.5, tauxVictoire: 50 },
  },
];

export const joueurParId = (id: string) => joueurs.find((j) => j.id === id);
export const clubParId = (id: string) => clubs.find((c) => c.id === id);

// ---------------------------------------------------------------------------
// POSTS / FEED
// ---------------------------------------------------------------------------

export const posts: Post[] = [
  {
    id: "p1",
    auteurType: "club",
    auteurId: "african-fc",
    auteurNom: "African FC",
    auteurAvatar: "african-fc",
    auteurVerifie: true,
    contenu:
      "🔥 VICTOIRE 4-1 contre Dragons Élite ! Une masterclass collective ce soir. Le projet African FC continue son ascension vers les sommets. #ClubProFC27",
    clipBut: true,
    date: "2026-08-14T21:32:00",
    likes: 3420,
    commentaires: 214,
    partages: 156,
  },
  {
    id: "p2",
    auteurType: "joueur",
    auteurId: "j1",
    auteurNom: "Kwame_Finisher",
    auteurAvatar: "j1",
    auteurVerifie: true,
    contenu: "Triplé ce soir avec African FC. La forme est bonne, on continue de grimper 📈⚽",
    clipBut: true,
    date: "2026-08-14T21:50:00",
    likes: 1820,
    commentaires: 98,
    partages: 44,
  },
  {
    id: "p3",
    auteurType: "joueur",
    auteurId: "j10",
    auteurNom: "MaxGoal_FR",
    auteurAvatar: "j10",
    auteurVerifie: false,
    contenu:
      "🔍 Libre de tout contrat ! Buteur confirmé (61 buts la saison passée), niveau 60, dispo soir et week-end. DM ouverts pour les clubs sérieux.",
    date: "2026-08-16T18:10:00",
    likes: 210,
    commentaires: 32,
    partages: 18,
  },
  {
    id: "p4",
    auteurType: "club",
    auteurId: "c3",
    auteurNom: "Nova United",
    auteurAvatar: "c3",
    auteurVerifie: false,
    contenu:
      "Recrutement ouvert ! On cherche un BU archétype Poacher niveau 70+. Essais organisés ce week-end. Postulez via notre page recrutement.",
    date: "2026-08-16T14:00:00",
    likes: 87,
    commentaires: 21,
    partages: 9,
  },
  {
    id: "p5",
    auteurType: "joueur",
    auteurId: "j2",
    auteurNom: "Sekou_Playmaker",
    auteurAvatar: "j2",
    auteurVerifie: true,
    contenu: "96 passes décisives cette saison. Merci à mes attaquants de conclure 🙏 On vise le titre.",
    date: "2026-08-15T10:22:00",
    likes: 940,
    commentaires: 54,
    partages: 21,
  },
  {
    id: "p6",
    auteurType: "club",
    auteurId: "african-fc",
    auteurNom: "African FC",
    auteurAvatar: "african-fc",
    auteurVerifie: true,
    contenu:
      "📢 ANNONCE : African FC ouvre officiellement son recrutement mondial. On cherche les meilleurs talents, peu importe la région. Postulez dès maintenant sur notre page vitrine !",
    date: "2026-08-13T09:00:00",
    likes: 5210,
    commentaires: 412,
    partages: 890,
  },
  {
    id: "p7",
    auteurType: "joueur",
    auteurId: "j4",
    auteurNom: "Boubacar_Fox",
    auteurAvatar: "j4",
    auteurVerifie: true,
    contenu: "Nouveau record de vitesse en match : sprint à 96 sur l'aile droite 💨",
    date: "2026-08-12T20:15:00",
    likes: 670,
    commentaires: 40,
    partages: 12,
  },
  {
    id: "p8",
    auteurType: "club",
    auteurId: "c5",
    auteurNom: "Atlas Warriors",
    auteurAvatar: "c5",
    auteurVerifie: true,
    contenu: "Tournoi Coupe du Maghreb : nous voilà en finale ! Rendez-vous samedi pour le multiplex.",
    date: "2026-08-11T17:40:00",
    likes: 312,
    commentaires: 28,
    partages: 15,
  },
];

export const stories: Story[] = [
  { id: "s1", auteurId: "african-fc", auteurNom: "African FC", auteurAvatar: "african-fc", vue: false, couleur: "#0f9d58" },
  { id: "s2", auteurId: "j1", auteurNom: "Kwame", auteurAvatar: "j1", vue: false, couleur: "#0f9d58" },
  { id: "s3", auteurId: "j2", auteurNom: "Sekou", auteurAvatar: "j2", vue: false, couleur: "#d4af37" },
  { id: "s4", auteurId: "c2", auteurNom: "Dragons Élite", auteurAvatar: "c2", vue: true, couleur: "#dc2626" },
  { id: "s5", auteurId: "j4", auteurNom: "Boubacar", auteurAvatar: "j4", vue: false, couleur: "#facc15" },
  { id: "s6", auteurId: "c5", auteurNom: "Atlas Warriors", auteurAvatar: "c5", vue: true, couleur: "#059669" },
  { id: "s7", auteurId: "j10", auteurNom: "MaxGoal", auteurAvatar: "j10", vue: false, couleur: "#dc2626" },
];

// ---------------------------------------------------------------------------
// RECRUTEMENT / TRANSFERTS
// ---------------------------------------------------------------------------

export const annonces: AnnonceRecrutement[] = [
  {
    id: "a1",
    type: "club",
    auteurId: "african-fc",
    auteurNom: "African FC",
    auteurLogo: "african-fc",
    titre: "Recherche Buteur d'élite — Archétype Finisseur",
    poste: "BU",
    archetype: "Finisseur",
    niveauMin: 85,
    disponibilite: "Soir (19h-00h) + week-end",
    langues: ["Français", "Anglais"],
    region: "Côte d'Ivoire",
    description: "Projet African FC : rejoignez le meilleur collectif du continent. Essais sur invitation uniquement.",
    date: "2026-08-15",
  },
  {
    id: "a2",
    type: "club",
    auteurId: "african-fc",
    auteurNom: "African FC",
    auteurLogo: "african-fc",
    titre: "Recherche Gardien — Archétype Réflexes",
    poste: "GB",
    archetype: "Gardien Réflexes",
    niveauMin: 82,
    disponibilite: "Soir + week-end",
    langues: ["Français"],
    region: "Côte d'Ivoire",
    description: "Un dernier rempart de très haut niveau pour accompagner notre ascension en Champions.",
    date: "2026-08-14",
  },
  {
    id: "a3",
    type: "club",
    auteurId: "c3",
    auteurNom: "Nova United",
    auteurLogo: "c3",
    titre: "BU Poacher niveau 70+ recherché",
    poste: "BU",
    archetype: "Poacher",
    niveauMin: 70,
    disponibilite: "Week-end",
    langues: ["Français"],
    region: "Belgique",
    description: "Club en progression cherche un finisseur pour la fin de saison.",
    date: "2026-08-16",
  },
  {
    id: "a4",
    type: "club",
    auteurId: "c2",
    auteurNom: "Dragons Élite",
    auteurLogo: "c2",
    titre: "Ailier rapide + Sentinelle recherchés",
    poste: "AD",
    archetype: "Ailier Rapide",
    niveauMin: 75,
    disponibilite: "Soir",
    langues: ["Français", "Anglais"],
    region: "France",
    description: "Deux postes ouverts pour compléter l'effectif avant les phases finales.",
    date: "2026-08-13",
  },
  {
    id: "a5",
    type: "joueur",
    auteurId: "j10",
    auteurNom: "MaxGoal_FR",
    auteurLogo: "j10",
    titre: "Buteur libre — 61 buts la saison passée",
    poste: "BU",
    archetype: "Poacher",
    niveauMin: 60,
    disponibilite: "Soir et week-end",
    langues: ["Français", "Anglais"],
    region: "France",
    description: "Ex-Dragons Élite, cherche un projet ambitieux visant la montée.",
    date: "2026-08-16",
  },
  {
    id: "a6",
    type: "joueur",
    auteurId: "j15",
    auteurNom: "Amara_Diallo",
    auteurLogo: "j15",
    titre: "Meneur de jeu libre, disponible immédiatement",
    poste: "MOC",
    archetype: "Meneur de Jeu Avancé",
    niveauMin: 58,
    disponibilite: "Soir et week-end",
    langues: ["Français", "Anglais"],
    region: "Sénégal",
    description: "24 passes décisives cette saison. Cherche club sérieux visant l'Élite.",
    date: "2026-08-15",
  },
  {
    id: "a7",
    type: "club",
    auteurId: "c5",
    auteurNom: "Atlas Warriors",
    auteurLogo: "c5",
    titre: "Latéral offensif recherché",
    poste: "DD",
    archetype: "Latéral Offensif",
    niveauMin: 72,
    disponibilite: "Soir",
    langues: ["Français", "Arabe"],
    region: "Maroc",
    description: "Complément d'effectif pour la campagne de Coupe du Maghreb.",
    date: "2026-08-12",
  },
];

export const transferts: Transfert[] = [
  {
    id: "t1",
    joueurId: "j1",
    joueurNom: "Kwame_Finisher",
    joueurAvatar: "j1",
    clubDepartId: "c5",
    clubDepartNom: "Atlas Warriors",
    clubArriveeId: "african-fc",
    clubArriveeNom: "African FC",
    clubArriveeLogo: "african-fc",
    poste: "BU",
    date: "2024-06-01",
    type: "Transfert",
  },
  {
    id: "t2",
    joueurId: "j3",
    joueurNom: "Yannick_Wall",
    joueurAvatar: "j3",
    clubArriveeId: "african-fc",
    clubArriveeNom: "African FC",
    clubArriveeLogo: "african-fc",
    poste: "DC",
    date: "2025-01-15",
    type: "Arrivée libre",
  },
  {
    id: "t3",
    joueurId: "j13",
    joueurNom: "Kilian_Ice",
    joueurAvatar: "j13",
    clubArriveeId: "c3",
    clubArriveeNom: "Nova United",
    clubArriveeLogo: "c3",
    poste: "GB",
    date: "2026-08-10",
    type: "Prêt",
  },
];

// ---------------------------------------------------------------------------
// LIVE
// ---------------------------------------------------------------------------

export const liveMatches: LiveMatch[] = [
  {
    id: "l1",
    titre: "Choc au sommet — Ligue Continentale J12",
    clubDomicile: "African FC",
    clubDomicileLogo: "african-fc",
    clubExterieur: "Dragons Élite",
    clubExterieurLogo: "c2",
    scoreDomicile: 2,
    scoreExterieur: 1,
    minute: 67,
    spectateurs: 3240,
    streamer: "African FC Officiel",
    plateforme: "Natif",
    thumbnail: "african-fc",
    isLive: true,
    competition: "Ligue Continentale",
  },
  {
    id: "l2",
    titre: "Nova United vs Titan FC",
    clubDomicile: "Nova United",
    clubDomicileLogo: "c3",
    clubExterieur: "Titan FC",
    clubExterieurLogo: "c6",
    scoreDomicile: 0,
    scoreExterieur: 0,
    minute: 23,
    spectateurs: 540,
    streamer: "NovaTV",
    plateforme: "Twitch",
    thumbnail: "c3",
    isLive: true,
    competition: "Division 4",
  },
  {
    id: "l3",
    titre: "Phoenix Sporting vs Atlas Warriors",
    clubDomicile: "Phoenix Sporting",
    clubDomicileLogo: "c4",
    clubExterieur: "Atlas Warriors",
    clubExterieurLogo: "c5",
    scoreDomicile: 3,
    scoreExterieur: 2,
    minute: 88,
    spectateurs: 1120,
    streamer: "PhoenixCast",
    plateforme: "YouTube",
    thumbnail: "c4",
    isLive: true,
    competition: "Coupe des Nations",
  },
  {
    id: "l4",
    titre: "Replay — Finale Coupe de Printemps",
    clubDomicile: "Dragons Élite",
    clubDomicileLogo: "c2",
    clubExterieur: "African FC",
    clubExterieurLogo: "african-fc",
    scoreDomicile: 1,
    scoreExterieur: 3,
    minute: 90,
    spectateurs: 8900,
    streamer: "ClubProFC27",
    plateforme: "Natif",
    thumbnail: "african-fc",
    isLive: false,
    competition: "Coupe de Printemps",
  },
];

export const chatMessages: ChatMessage[] = [
  { id: "cm1", auteur: "FanAFC_01", avatar: "j2", message: "ALLEZ AFRICAN FC 🔥🔥🔥", date: "21:41" },
  { id: "cm2", auteur: "DragonsFor Life", avatar: "j9", message: "Belle occasion pour Dragons là", date: "21:41" },
  { id: "cm3", auteur: "ProClubsFan", avatar: "j10", message: "Kwame est injouable ce soir", date: "21:42" },
  { id: "cm4", auteur: "Sekou_Playmaker", avatar: "j2", message: "On garde le rythme les gars 💪", couleur: "#0f9d58", date: "21:42" },
  { id: "cm5", auteur: "ViewerNL", avatar: "j12", message: "quel level ce match", date: "21:43" },
];

// ---------------------------------------------------------------------------
// TOURNOIS
// ---------------------------------------------------------------------------

export const tournois: Tournoi[] = [
  {
    id: "tn1",
    nom: "Ligue Continentale — Playoffs",
    image: "african-fc",
    format: "11 vs 11",
    dateDebut: "2026-08-20",
    dateFin: "2026-09-05",
    clubsInscrits: 16,
    clubsMax: 16,
    cashprize: "5 000 €",
    sponsorise: true,
    statut: "À venir",
    regles: [
      "Format effectif complet 11v11",
      "Matchs aller-retour en phase de poules",
      "Élimination directe à partir des quarts",
      "Fair-play obligatoire, tout comportement toxique sanctionné",
    ],
    organisateur: "Club Pro FC 27",
  },
  {
    id: "tn2",
    nom: "Coupe des Nations Pro Clubs",
    image: "c5",
    format: "11 vs 11",
    dateDebut: "2026-07-01",
    dateFin: "2026-08-10",
    clubsInscrits: 32,
    clubsMax: 32,
    cashprize: "10 000 €",
    sponsorise: true,
    statut: "Terminé",
    regles: ["Phase de groupes puis élimination directe", "3 remplacements par match"],
    organisateur: "FC27 Esport League",
    vainqueur: "African FC",
  },
  {
    id: "tn3",
    nom: "Coupe de Printemps Amateur",
    image: "c3",
    format: "11 vs 11",
    dateDebut: "2026-09-10",
    dateFin: "2026-09-25",
    clubsInscrits: 8,
    clubsMax: 16,
    sponsorise: false,
    statut: "À venir",
    regles: ["Ouvert à tous les clubs Division 4 et moins", "Effectif minimum 8 joueurs requis"],
    organisateur: "Nova United",
  },
  {
    id: "tn4",
    nom: "Cup Battle Royale 4v4",
    image: "c4",
    format: "4 vs 4",
    dateDebut: "2026-08-25",
    dateFin: "2026-08-27",
    clubsInscrits: 24,
    clubsMax: 32,
    cashprize: "1 500 €",
    sponsorise: true,
    statut: "À venir",
    regles: ["Format rapide 4v4", "Matchs en un set, prolongations si égalité"],
    organisateur: "Phoenix Sporting",
  },
];

export const bracketDemo = (): import("@/types").BracketMatch[] => [
  { id: "bm1", round: 1, position: 1, clubA: "African FC", clubALogo: "african-fc", clubB: "Titan FC", clubBLogo: "c6", scoreA: 4, scoreB: 1, vainqueur: "African FC", statut: "Terminé" },
  { id: "bm2", round: 1, position: 2, clubA: "Dragons Élite", clubALogo: "c2", clubB: "Nova United", clubBLogo: "c3", scoreA: 2, scoreB: 2, vainqueur: "Dragons Élite", statut: "Terminé" },
  { id: "bm3", round: 1, position: 3, clubA: "Phoenix Sporting", clubALogo: "c4", clubB: "Atlas Warriors", clubBLogo: "c5", scoreA: 1, scoreB: 3, vainqueur: "Atlas Warriors", statut: "Terminé" },
  { id: "bm4", round: 1, position: 4, clubA: "Titan FC", clubALogo: "c6", clubB: "African FC", clubBLogo: "african-fc", statut: "À venir" },
  { id: "bm5", round: 2, position: 1, clubA: "African FC", clubALogo: "african-fc", clubB: "Dragons Élite", clubBLogo: "c2", scoreA: 3, scoreB: 0, vainqueur: "African FC", statut: "Terminé" },
  { id: "bm6", round: 2, position: 2, clubA: "Atlas Warriors", clubALogo: "c5", clubB: "?", statut: "En cours" },
  { id: "bm7", round: 3, position: 1, clubA: "African FC", clubALogo: "african-fc", clubB: "?", statut: "À venir" },
];

// ---------------------------------------------------------------------------
// MATCHMAKING
// ---------------------------------------------------------------------------

export const matchsRapides: MatchRapide[] = [
  { id: "mr1", format: "2v2", adversaire: "Team Falcon", adversaireAvatar: "j9", resultat: "Victoire", score: "5 - 2", date: "2026-08-16T20:10:00" },
  { id: "mr2", format: "1v1", adversaire: "Zizou_Pro", adversaireAvatar: "j10", resultat: "Défaite", score: "1 - 2", date: "2026-08-16T19:40:00" },
  { id: "mr3", format: "3v3", adversaire: "Team Nova", adversaireAvatar: "j12", resultat: "Victoire", score: "4 - 3", date: "2026-08-15T21:00:00" },
  { id: "mr4", format: "4v4", adversaire: "Squad Phoenix", adversaireAvatar: "j14", resultat: "Nul", score: "2 - 2", date: "2026-08-14T18:30:00" },
];

// ---------------------------------------------------------------------------
// CLASSEMENT
// ---------------------------------------------------------------------------

export const classement: ClassementClub[] = clubs
  .slice()
  .sort((a, b) => b.classementElo - a.classementElo)
  .map((club, i) => ({
    rang: i + 1,
    ancienRang: i === 0 ? 1 : i === 2 ? 2 : i === 1 ? 3 : i + 1,
    club,
    elo: club.classementElo,
    serie: (["V", "V", "N", "V", "D"] as ("V" | "D" | "N")[]).slice(0, 5),
  }));

// ---------------------------------------------------------------------------
// MESSAGERIE
// ---------------------------------------------------------------------------

export const conversations: Conversation[] = [
  {
    id: "conv1",
    type: "groupe",
    nom: "African FC — Vestiaire",
    avatar: "african-fc",
    dernierMessage: "Sekou_Playmaker: On garde le rythme les gars 💪",
    dateDernierMessage: "2026-08-16T21:42:00",
    nonLu: 3,
    enLigne: true,
  },
  {
    id: "conv2",
    type: "prive",
    nom: "Kwame_Finisher",
    avatar: "j1",
    dernierMessage: "GG pour ce soir, triplé de fou 🔥",
    dateDernierMessage: "2026-08-16T22:05:00",
    nonLu: 1,
    enLigne: true,
  },
  {
    id: "conv3",
    type: "prive",
    nom: "MaxGoal_FR",
    avatar: "j10",
    dernierMessage: "Ok je suis dispo pour un essai ce week-end",
    dateDernierMessage: "2026-08-16T17:20:00",
    nonLu: 0,
    enLigne: false,
  },
  {
    id: "conv4",
    type: "groupe",
    nom: "Nova United — Recrutement",
    avatar: "c3",
    dernierMessage: "Tom_Vandaele: Les essais commencent à 20h",
    dateDernierMessage: "2026-08-15T19:00:00",
    nonLu: 0,
    enLigne: false,
  },
];

export const messagesParConversation: Record<string, MessagePrive[]> = {
  conv2: [
    { id: "m1", conversationId: "conv2", expediteur: "Kwame_Finisher", contenu: "GG pour ce soir, triplé de fou 🔥", date: "22:05", moi: false },
    { id: "m2", conversationId: "conv2", expediteur: "moi", contenu: "Merci frérot, le collectif a été énorme aussi", date: "22:06", moi: true },
    { id: "m3", conversationId: "conv2", expediteur: "Kwame_Finisher", contenu: "On garde ce rythme jusqu'à la finale", date: "22:07", moi: false },
  ],
  conv1: [
    { id: "m4", conversationId: "conv1", expediteur: "Yannick_Wall", contenu: "Belle défense collective ce soir", date: "21:38", moi: false },
    { id: "m5", conversationId: "conv1", expediteur: "Sekou_Playmaker", contenu: "On garde le rythme les gars 💪", date: "21:42", moi: false },
  ],
  conv3: [
    { id: "m6", conversationId: "conv3", expediteur: "moi", contenu: "Salut, ton profil est intéressant, tu es dispo pour un essai ?", date: "17:15", moi: true },
    { id: "m7", conversationId: "conv3", expediteur: "MaxGoal_FR", contenu: "Ok je suis dispo pour un essai ce week-end", date: "17:20", moi: false },
  ],
  conv4: [
    { id: "m8", conversationId: "conv4", expediteur: "Tom_Vandaele", contenu: "Les essais commencent à 20h", date: "19:00", moi: false },
  ],
};
